// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScesr8j70hH76ldpDgSti3DX3Huf45Dc',
    appId: '1:316406388592:web:0263b5a8c18145d7c4a1b5',
    messagingSenderId: '316406388592',
    projectId: 'zyla-534c8',
    authDomain: 'zyla-534c8.firebaseapp.com',
    storageBucket: 'zyla-534c8.firebasestorage.app',
    measurementId: 'G-861XJJW5ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXpMc5O7T4kHShfVXh4JyCNdnRz2cEDM',
    appId: '1:316406388592:android:a26a2e2b10953174c4a1b5',
    messagingSenderId: '316406388592',
    projectId: 'zyla-534c8',
    storageBucket: 'zyla-534c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywJ4ctuymPhTPolOm2To2jTYinzEP148',
    appId: '1:316406388592:ios:000676099d39aaf1c4a1b5',
    messagingSenderId: '316406388592',
    projectId: 'zyla-534c8',
    storageBucket: 'zyla-534c8.firebasestorage.app',
    iosBundleId: 'com.example.zyla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywJ4ctuymPhTPolOm2To2jTYinzEP148',
    appId: '1:316406388592:ios:000676099d39aaf1c4a1b5',
    messagingSenderId: '316406388592',
    projectId: 'zyla-534c8',
    storageBucket: 'zyla-534c8.firebasestorage.app',
    iosBundleId: 'com.example.zyla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScesr8j70hH76ldpDgSti3DX3Huf45Dc',
    appId: '1:316406388592:web:d6bfdf703a377e4ac4a1b5',
    messagingSenderId: '316406388592',
    projectId: 'zyla-534c8',
    authDomain: 'zyla-534c8.firebaseapp.com',
    storageBucket: 'zyla-534c8.firebasestorage.app',
    measurementId: 'G-9E8HD74ZGR',
  );
}
